import comp from "C:/Users/gudong/Desktop/gudongBlog-master/src/.vuepress/.temp/pages/文章/C语言复习3.html.vue"
const data = JSON.parse("{\"path\":\"/%E6%96%87%E7%AB%A0/C%E8%AF%AD%E8%A8%80%E5%A4%8D%E4%B9%A03.html\",\"title\":\"C语言数组与指针\",\"lang\":\"zh-CN\",\"frontmatter\":{\"icon\":\"pen-to-square\",\"date\":\"2024-09-25T00:00:00.000Z\",\"category\":[\"C语言\"],\"tag\":[\"Windows\",\"Visual studio\"],\"star\":true,\"description\":\"C语言数组与指针 C 语言支持数组数据结构，它可以存储一个固定大小的相同类型元素的顺序集合。数组是用来存储一系列数据，但它往往被认为是一系列相同类型的变量。 数组的声明并不是声明一个个单独的变量，比如 runoob0、runoob1、...、runoob99，而是声明一个数组变量，比如 runoob，然后使用 runoob[0]、runoob[1]、....\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://docs.200310.xyz/%E6%96%87%E7%AB%A0/C%E8%AF%AD%E8%A8%80%E5%A4%8D%E4%B9%A03.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"C语言数组与指针\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"C语言数组与指针 C 语言支持数组数据结构，它可以存储一个固定大小的相同类型元素的顺序集合。数组是用来存储一系列数据，但它往往被认为是一系列相同类型的变量。 数组的声明并不是声明一个个单独的变量，比如 runoob0、runoob1、...、runoob99，而是声明一个数组变量，比如 runoob，然后使用 runoob[0]、runoob[1]、....\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://blog.200310.xyz/usr/uploads/2024/02/2830112454.png \\\"c-arrays-2021-1-18-3.png\\\"\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"咕咚\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Windows\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Visual studio\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-09-25T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"C语言数组与指针\\\",\\\"image\\\":[\\\"https://blog.200310.xyz/usr/uploads/2024/02/2830112454.png \\\\\\\"c-arrays-2021-1-18-3.png\\\\\\\"\\\",\\\"https://blog.200310.xyz/usr/uploads/2024/02/1323222618.png \\\\\\\"c-array-2021-01-18-2.png\\\\\\\"\\\",\\\"https://blog.200310.xyz/usr/uploads/2024/02/3846327685.png \\\\\\\"屏幕截图 2024-02-20 230544.png\\\\\\\"\\\"],\\\"datePublished\\\":\\\"2024-09-25T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"咕咚\\\",\\\"url\\\":\\\"https://github.com/gydchenxiao\\\"}]}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":1.54,\"words\":463},\"filePathRelative\":\"文章/C语言复习3.md\",\"localizedDate\":\"2024年9月25日\",\"excerpt\":\"\\n<p>C 语言支持数组数据结构，它可以存储一个固定大小的相同类型元素的顺序集合。数组是用来存储一系列数据，但它往往被认为是一系列相同类型的变量。</p>\\n<p>数组的声明并不是声明一个个单独的变量，比如 runoob0、runoob1、...、runoob99，而是声明一个数组变量，比如 runoob，然后使用 runoob[0]、runoob[1]、...、runoob[99] 来代表一个个单独的变量。</p>\\n<p>所有的数组都是由连续的内存位置组成。最低的地址对应第一个元素，最高的地址对应最后一个元素。</p>\\n<p><img src=\\\"https://blog.200310.xyz/usr/uploads/2024/02/2830112454.png\\\" alt=\\\"c-arrays-2021-1-18-3.png\\\" title=\\\"c-arrays-2021-1-18-3.png\\\"></p>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
